# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46e77fdb1e16a7742366d17ceef2e3b2c93cb87da3aa7ab5252220d21702ddffb89059f4e6717b003d5bf9dba6150fac76addb2e5104a87cdbc5d754a7c8619

test:
  secret_key_base: 8934a91279019dc6654fd47808ba27c5860f3905c0892f338ebbf40ce7c1e26ddce1c5cb49fe9f9d0b7290b09355ccdb732cbc38d832134f31d25fea717e57ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
